### PR TITLE
[Clustering] Modernized C code to C++ (pybind11 binding)

### LINKED ISSUE #1139: [coordinates.cluster_kmeans] kernel restarting for bad choices of init_strategy
This is a bug that only occurs to users who don't constantly stick to the docs, but still: If one chooses a wrong `init_strategy` for `pyemma.coordinates.cluster_kmeans()`, i.e. passes a string that has no corresponding method, the ipython kernel crashes. Given this is reproducible, maybe a quick check for the available methods would be great. Here some minimal example (pyemma 2.4 and devel branch version).

```python
import pyemma
import numpy as np
rdata = np.random.random_sample(size=(10, 1000))
clustering = pyemma.coordinates.cluster_kmeans(rdata, k=20, init_strategy='k++')
```

### PR DESCRIPTION
**Pull request by marscher**
This greatly reduces the complexity of initializing metrics and binding to Python. It also avoids copying memory buffers for each calls. In my local benchmarks the new code is 10% faster (which is likely due to optimized memory transfers/cache hits).

The module now contains both regspace and kmeans(++) and could be easily extended due to an abstract base class. We can optionally/easily switch the input/return data type via templating.

I've tested both kmeans and regspace with BPTI data and they both converge to the same results.

Still some careful tests need to be performed for minRMSD metric, because we lack a good unit test here. Any suggestions for this are welcome! Eg. @nsplattner maybe you can give me a hint here.

This code can not be compiled on Python-2.7 / Windows, but we have agreed, that we will not support 2.7 anymore in #1140.

@clonker If you catch anything C++ related, please let me know. The code is functional and should not contain any more bugs (than it did before).

This also fixes #1139

### CODE REVIEW

**Comment by marscher** [comment]
win compilation failed only for 32 bit, mhm...

**Comment by marscher** [comment]
Forgot to mention that the Python interface of kmeans now supports to resume the iteration.
There are two new flags (maybe we can reduce them to one).

* init_strategy can be "resume" and clustercenters can be passed to iterate.
* keep_data (true, false): if the user intends to resume an non converged kmeans estimation, this should be set to true, to keep the in_memory chunks.

@gph82 does this fit our needs? You opened an issue about this once

**Comment by franknoe** [comment]
Is anyone still using 32 bit? 


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by marscher** [comment]
On 02.08.2017 22:12, Frank Noe wrote:
> 
> 
> Is anyone still using 32 bit?
It could be still installed on cheap OEM laptops (owned by poor phd 
students). Probably the usage statistics will give us some insights on 
that. But I guess your are right, it would not be worth the effort to fix.

File: pyemma/coordinates/clustering/include/bits/kmeans_bits.h [hunk 1]
```diff
@@ -0,0 +1,328 @@
...
+        }
+        (*(centers_counter_p + closest_center_index))++;
+        for (j = 0; j < dim; j++) {
+            new_centers(closest_center_index, j) += chunk(i, j);
+        }
+    }
+#else
+    omp_set_num_threads(n_threads);
+    std::vector<dtype> dists(N_centers);
+    #pragma omp parallel
```
Comment (jchodera) [inline pyemma/coordinates/clustering/include/bits/kmeans_bits.h]: Would it help to delineate which variables should be private and which should be shared? OpenMP sometimes can't figure this out on its own.

File: pyemma/coordinates/clustering/include/bits/kmeans_bits.h [hunk 2]
```diff
@@ -0,0 +1,328 @@
...
+    {
+    for (size_t i = 0; i < N_frames; ++i) {
```
Comment (jchodera) [inline pyemma/coordinates/clustering/include/bits/kmeans_bits.h]: Are you sure you want to parallelize the calculation over the number of centers (which may not be much larger than the number of threads), rather than the number of frames (which is pretty much guaranteed to be huge)? As long as the parallelization fetches contiguous chunks of frames into memory during parallelization, it should still be pretty quick for each thread to do a decent chunk of work in computing the distance to all centers before moving onto the next frame.

**Comment by marscher** [comment]
In C++, we should stick to RAII (locality of variables). This, in
contrast to C99, where we would need to declare everything before any
computation/assignment, automatically leads to thread isolated variables.

File: pyemma/coordinates/clustering/include/bits/kmeans_bits.h (hunk 2 above)
Comment (jchodera) [reply pyemma/coordinates/clustering/include/bits/kmeans_bits.h]: I think `#pragma omp parallel for schedule(static, 1)` would give a [chunksize of 1](https://software.intel.com/en-us/articles/openmp-loop-scheduling) to make sure the threads progress through the frames in contiguous chunks.

File: pyemma/coordinates/clustering/include/bits/kmeans_bits.h [hunk 3]
```diff
@@ -0,0 +1,328 @@
...
+        auto mindist = std::numeric_limits<dtype>::max();
+        #pragma omp for
+        for (size_t j = 0; j < N_centers; ++j) {
+            dists[j] = parent_t::metric->compute(&chunk(i, 0), &centers(j, 0));
+        }
+        #pragma omp flush(dists)
```
Comment (jchodera) [inline pyemma/coordinates/clustering/include/bits/kmeans_bits.h]: If each thread handles its own frame, you wouldn't need to synchronize `dists` across threads---this could be a thread-private variable, since each thread would figure out which center to assign its frame to on its own. This should have some speed advantages by avoiding the need for synchronization.

Comment (marscher) [reply pyemma/coordinates/clustering/include/bits/kmeans_bits.h]: 👍

File: pyemma/coordinates/clustering/include/bits/kmeans_bits.h [hunk 4]
```diff
@@ -0,0 +1,328 @@
...
+        callback();
+    }
+#ifdef USE_OPENMP
+    omp_set_num_threads(n_threads);
+#endif
+
+    /* iterate over all data points j, measuring the squared distance between j and the initial center i: */
+    /* squared_distances[i] = distance(x_j, x_i)*distance(x_j, x_i) */
+    dtype dist_sum = 0.0;
+    #pragma omp parallel for
```
Comment (jchodera) [inline pyemma/coordinates/clustering/include/bits/kmeans_bits.h]: I don't think we can parallelize this by frames since the state when processing frame `n` depends on the outcome of processing frames `1...(n-1)`. I think the only true parallelism here to end up with a deterministic outcome is to parallelize the distance calculation to existing centers. 

In reality, anyone who wants to really parallelize this would use the equitemporal initialization, since this is trivially parallelizable.

Comment (marscher) [reply pyemma/coordinates/clustering/include/bits/kmeans_bits.h]: equitemporal init? What do you mean by that?

Comment (jchodera) [reply pyemma/coordinates/clustering/include/bits/kmeans_bits.h]: I might be misreading the docs, but doesn't [`init_strategy='uniform'`](http://www.emma-project.org/latest/api/generated/pyemma.coordinates.clustering.KmeansClustering.html#pyemma.coordinates.clustering.KmeansClustering) select initial generators in a non-history-dependent way?

**Comment by marscher** [comment]
Thanks for your suggestions. I'll now leave and enjoy the weekend.
The parallelisation works and is pretty fast, please feel free to fine tune my openmp stupidity.

Still need to figure out, why seed test for kmeans fails, even with njobs=1, this leads to different centers result.

**Comment by jchodera** [comment]
Thanks so much, and have a great weekend, @marscher! We'll give this a try and report back, opening a PR to tweak the OpenMP parallelization if we find a way to improve on what you've already done!

**Comment by marscher** [comment]
I was not aware that a simple break in a parallel for loop does not cancel all threads. http://jakascorner.com/blog/2016/08/omp-cancel.html

**Comment by marscher** [comment]
@jchodera I've fixed some issues with openmp and validated the results. If still see some space for improvements, I'd very happy if you can comment on this again or open up a PR to change this stuff.

File: pyemma/coordinates/clustering/include/bits/kmeans_bits.h [hunk 5]
```diff
@@ -0,0 +1,336 @@
...
+#else
+    omp_set_num_threads(n_threads);
+
+    #pragma omp parallel for
+    for (size_t i = 0; i < N_frames; ++i) {
+        std::vector<dtype> dists(N_centers);
+        for (size_t j = 0; j < N_centers; ++j) {
+            dists[j] = parent_t::metric->compute(&chunk(i, 0), &centers(j, 0));
+        }
+        #pragma omp flush(dists)
```
Comment (jchodera) [inline pyemma/coordinates/clustering/include/bits/kmeans_bits.h]: Shouldn't `dists` be made thread-local at this point, so that there is no more need to `flush(dists)` since we don't need to synchronize between threads to find the closest center?

File: pyemma/coordinates/clustering/include/bits/kmeans_bits.h [hunk 6]
```diff
@@ -0,0 +1,336 @@
...
+
+    dtype value = 0.0;
+    //std::atomic<dtype> value;
+    //value = 0.0;
+    std::size_t n_frames = np_data.shape(0);
+    #ifdef USE_OPENMP
+    omp_set_num_threads(n_threads);
+    #endif
+
+    #pragma omp parallel for reduction(+:value)
```
Comment (jchodera) [inline pyemma/coordinates/clustering/include/bits/kmeans_bits.h]: I think these `omp parallel for` loops could be forced to move through thread-blocks of local chunks of memory by adding `schedule(static, 1)`: https://software.intel.com/en-us/articles/openmp-loop-scheduling

File: pyemma/coordinates/clustering/include/bits/kmeans_bits.h [hunk 7]
```diff
@@ -0,0 +1,336 @@
...
+        centers_counter.at(closest_center_index)++;
+        //(*(centers_counter_p + closest_center_index))++;
+        for (j = 0; j < dim; j++) {
+            new_centers(closest_center_index, j) += chunk(i, j);
+        }
+    }
+#else
+    omp_set_num_threads(n_threads);
+
+    #pragma omp parallel for
```
Comment (jchodera) [inline pyemma/coordinates/clustering/include/bits/kmeans_bits.h]: I think these `omp parallel for` loops could be forced to march through compact sets of `n_threads` frames (to avoid the need to pull in nonlocal sets of frames into memory) by adding the `schedule(static, 1)` keywords: https://software.intel.com/en-us/articles/openmp-loop-scheduling

**Comment by jchodera** [comment]
> I'd very happy if you can comment on this again or open up a PR to change this stuff.

I'm traveling in Edinburgh right now, so apologies for not being able to contribute PRs directly!

@rafwiewiora is testing this locally, though, and should be able to provide direct performance feedback on real datasets!

**Comment by rafwiewiora** [comment]
@marscher thanks for doing this so quickly, much appreciated!!

Here's my results - we're running a ~ 1M frames (a 10-strided ~10M dataset), ~ 4.5k TICs dataset, into 1k, 2k, 3k, 4k, 5k clusters. Comparison is between: a) jobs run on 16 threads, but with the old non-parallelized code, using `pyemma.coordinates.source` with `chunk_size=5000` (so might be slower than it would be completely in memory I guess), b) jobs run on 16 threads, completely in memory (with `pyemma.coordinates.load`), with the code here as it was before the weekend. I'm starting: c) as b, but with the current code here now. 

I had 2 problems before I got it to run:

1) at installation from repo:
```
In file included from pyemma/coordinates/clustering/include/regspace.h:9:0,
                 from pyemma/coordinates/clustering/src/clustering_module.cpp:5:
pyemma/coordinates/clustering/include/Clustering.h:9:31: fatal error: pybind11/pybind11.h: No such file or directory
 #include <pybind11/pybind11.h>
                               ^
compilation terminated.
error: command 'gcc' failed with exit status 1
```

this was solved by `conda install pybind11`. 

2) on running:
```
initialize kmeans++ centers: 100% (100/100) [######################] eta 00:01 -Traceback (most recent call last):
  File "dih_kmeans_inmem.py", line 15, in <module>
    clustering = pyemma.coordinates.cluster_kmeans(data=data, k=nclusters, max_iter=1000, stride=10)
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyEMMA-2.4+188.ge6a74ec-py3.6-linux-x86_64.egg/pyemma/coordinates/api.py", line 1484, in cluster_kmeans
    return _param_stage(data, res, stride=stride, chunk_size=chunk_size)
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyEMMA-2.4+188.ge6a74ec-py3.6-linux-x86_64.egg/pyemma/coordinates/api.py", line 847, in _param_stage
    this_stage.estimate(X=input_stage, stride=stride)
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyEMMA-2.4+188.ge6a74ec-py3.6-linux-x86_64.egg/pyemma/coordinates/data/_base/transformer.py", line 222, in estimate
    super(StreamingEstimationTransformer, self).estimate(X, **kwargs)
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyEMMA-2.4+188.ge6a74ec-py3.6-linux-x86_64.egg/pyemma/coordinates/data/_base/streaming_estimator.py", line 51, in estimate
    super(StreamingEstimator, self).estimate(X, **kwargs)
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyEMMA-2.4+188.ge6a74ec-py3.6-linux-x86_64.egg/pyemma/_base/estimator.py", line 369, in estimate
    self._model = self._estimate(X)
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyEMMA-2.4+188.ge6a74ec-py3.6-linux-x86_64.egg/pyemma/coordinates/clustering/kmeans.py", line 219, in _estimate
    from matplotlib import pyplot as plt
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 26, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt4 import QtCore, QtGui
ModuleNotFoundError: No module named 'PyQt4'
```

`conda install 'pyqt < 5'` (because `conda list` had `pyqt                      5.6.0                    py36_2`) fails:

```
-bash-4.1$ conda install 'pyqt<5'
Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator
  - pyqt <5
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

but it was resolved by `conda install qt=4` which however forced me down to python 3.5 and re-installed all my packages. 

Now results:

1k clusters:

a)
`initialize kmeans++ centers:   1% (  10/1000) [                 ] eta 16:37:41 |`
`kmeans iterations:   0% (   2/1000) [                         ] eta 3753:00:32 |`

b) 
`initialize kmeans++ centers:   1% (  10/1000) [                  ] eta 2:25:20 |`
`kmeans iterations:   0% (   2/1000) [                         ] eta 2340:17:11 |`

6.9x k-means++, 1.6x k-means

2k clusters:

a)
`initialize kmeans++ centers:   1% (  20/2000) [                 ] eta 35:36:07 -`
killed job before kmeans++ finished, re-run with `uniform` initialization:
`kmeans iterations:   0% (   2/1000) [                         ] eta 7429:34:11 |`


b)
`initialize kmeans++ centers:   1% (  20/2000) [                  ] eta 3:04:59 -`
`kmeans iterations:   0% (   2/1000) [                         ] eta 4067:43:16 |`

11.6x k-means++, 1.8x k-means

3k clusters:

a)
`initialize kmeans++ centers:   1% (  30/3000) [                 ] eta 58:54:10 |`
killed job before kmeans++ finished, re-run with `uniform` initialization:
`kmeans iterations:   0% (   2/1000) [                        ] eta 11114:37:13 |`

b)
`initialize kmeans++ centers:   1% (  30/3000) [                  ] eta 4:57:33 |`
`kmeans iterations:   0% (   2/1000) [                         ] eta 6082:55:04 |`

11.9x k-means++, 1.8x k-means

4k clusters:

a)
`initialize kmeans++ centers:   1% (  40/4000) [                 ] eta 72:14:05 -`
killed job before kmeans++ finished, re-run with `uniform` initialization:
`kmeans iterations:   0% (   2/1000) [                        ] eta 15112:29:23 |`

b)
`initialize kmeans++ centers:   1% (  40/4000) [                  ] eta 6:55:40 -`
`kmeans iterations:   0% (   2/1000) [                         ] eta 8842:17:33 |`

10.4x k-means++, 1.71x k-means

5k clusters:

a)
`initialize kmeans++ centers:   1% (  50/5000) [                 ] eta 96:04:59 |`
killed job before kmeans++ finished, re-run with `uniform` initialization:
`kmeans iterations:   0% (   2/1000) [                        ] eta 19245:24:34 |`

b)
`initialize kmeans++ centers:   1% (  50/5000) [                  ] eta 8:25:50 |`
Converged after 2 iterations, no ETA recorded in log.

11.4x k-means++, unknown k-means

So this has made k-means++ reasonably fast now, but the speedup of the k-means itself is much lower than expected no? Again, this is 16 threads - how much speedup did you expect?

**Comment by marscher** [comment]
On 08.08.2017 00:05, Rafal Wiewiora wrote:
> @marscher <https://github.com/marscher> thanks for doing this so 
> quickly, much appreciated!!
> 
> Here's my results - we're running a ~ 1M frames (a 10-strided ~10M 
> dataset), ~ 4.5k TICs dataset, into 1k, 2k, 3k, 4k, 5k clusters. 
> Comparison is between: a) jobs run on 16 threads, but will the old 
> non-parallelized code, using |pyemma.coordinates.source| with 
> |chunk_size=5000| (so might be slower than it would be completely in 
> memory I guess), b) jobs run on 16 threads, completely in memory (with 
> |pyemma.coordinates.load|), with the code here as it was before the 
> weekend. I'm starting: c) as b, but with the current code here now.
> 
> I had 2 problems before I got it to run:
> 
>  1. at installation from repo:
> 
> |In file included from 
> pyemma/coordinates/clustering/include/regspace.h:9:0, from 
> pyemma/coordinates/clustering/src/clustering_module.cpp:5: 
> pyemma/coordinates/clustering/include/Clustering.h:9:31: fatal error: 
> pybind11/pybind11.h: No such file or directory #include 
> <pybind11/pybind11.h> ^ compilation terminated. error: command 'gcc' 
> failed with exit status 1 |
this should not happen, because pybind11 is a build time dependency, 
which should be installed automatically upon building extension. How did 
you install the development version?
> 
> this was solved by |conda install pybind11|.
> 
>  2. on running:
> 
> |initialize kmeans++ centers: 100% (100/100) [######################] eta 
> 00:01 -Traceback (most recent call last): File "dih_kmeans_inmem.py", 
> line 15, in <module> clustering = 
> pyemma.coordinates.cluster_kmeans(data=data, k=nclusters, max_iter=1000, 
> stride=10) File 
> "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyEMMA-2.4+188.ge6a74ec-py3.6-linux-x86_64.egg/pyemma/coordinates/api.py", 
> line 1484, in cluster_kmeans return _param_stage(data, res, 
> stride=stride, chunk_size=chunk_size) File 
> "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyEMMA-2.4+188.ge6a74ec-py3.6-linux-x86_64.egg/pyemma/coordinates/api.py", 
> line 847, in _param_stage this_stage.estimate(X=input_stage, 
> stride=stride) File 
> "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyEMMA-2.4+188.ge6a74ec-py3.6-linux-x86_64.egg/pyemma/coordinates/data/_base/transformer.py", 
> line 222, in estimate super(StreamingEstimationTransformer, 
> self).estimate(X, **kwargs) File 
> "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyEMMA-2.4+188.ge6a74ec-py3.6-linux-x86_64.egg/pyemma/coordinates/data/_base/streaming_estimator.py", 
> line 51, in estimate super(StreamingEstimator, self).estimate(X, 
> **kwargs) File 
> "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyEMMA-2.4+188.ge6a74ec-py3.6-linux-x86_64.egg/pyemma/_base/estimator.py", 
> line 369, in estimate self._model = self._estimate(X) File 
> "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/pyEMMA-2.4+188.ge6a74ec-py3.6-linux-x86_64.egg/pyemma/coordinates/clustering/kmeans.py", 
> line 219, in _estimate from matplotlib import pyplot as plt File 
> "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", 
> line 115, in <module> _backend_mod, new_figure_manager, 
> draw_if_interactive, _show = pylab_setup() File 
> "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/matplotlib/backends/__init__.py", 
> line 32, in pylab_setup globals(),locals(),[backend_name],0) File 
> "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", 
> line 16, in <module> from .backend_qt5 import QtCore File 
> "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", 
> line 26, in <module> import matplotlib.backends.qt_editor.figureoptions 
> as figureoptions File 
> "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", 
> line 20, in <module> import matplotlib.backends.qt_editor.formlayout as 
> formlayout File 
> "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", 
> line 56, in <module> from matplotlib.backends.qt_compat import QtGui, 
> QtWidgets, QtCore File 
> "/cbio/jclab/home/rafal.wiewiora/anaconda3/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", 
> line 137, in <module> from PyQt4 import QtCore, QtGui 
> ModuleNotFoundError: No module named 'PyQt4' |
> 
> |conda install 'pyqt < 5'| fails:
> 
> |-bash-4.1$ conda install 'pyqt<5' Fetching package metadata 
> ............... Solving package specifications: . UnsatisfiableError: 
> The following specifications were found to be in conflict: - 
> anaconda-navigator - pyqt <5 - python 3.6* Use "conda info <package>" to 
> see the dependencies for each package. |
> 
> but it was resolved by |conda install qt=4| which however forced me down 
> to python 3.5 and re-installed all my packages.
this is totally unrelated. The kmeans python code still plots the 
centers after initialization for visual inspection. This debug code will 
be removed later. I guess your matplotlibrc (if existent) chooses an 
interactive backend (QT), which is usually not available on clusters.
> 
> Now results:
Thanks for the results, which commit id did you test?
The fixed version is 888a81c3e6fefd7b697c589eedcca36f30980b40 and from 
the stacktrace of the matplotlib error, I see that you've tested an 
outdated version (sorry). The older version also contained a bug in the 
synchronization of the kmeans iteration method.

> 
> 1k clusters:
> 
> a)
> |initialize kmeans++ centers: 1% ( 10/1000) [ ] eta 16:37:41 ||
> |kmeans iterations: 0% ( 2/1000) [ ] eta 3753:00:32 ||
> 
> b)
> |initialize kmeans++ centers: 1% ( 10/1000) [ ] eta 2:25:20 ||
> |kmeans iterations: 0% ( 2/1000) [ ] eta 2340:17:11 ||
> 
> 6.9x k-means++, 1.6x k-means
> 
> 2k clusters:
> 
> a)
> |initialize kmeans++ centers: 1% ( 20/2000) [ ] eta 35:36:07 -|
> killed job before kmeans++ finished, re-run with |uniform| initialization:
> |kmeans iterations: 0% ( 2/1000) [ ] eta 7429:34:11 ||
> 
> b)
> |initialize kmeans++ centers: 1% ( 20/2000) [ ] eta 3:04:59 -|
> |kmeans iterations: 0% ( 2/1000) [ ] eta 4067:43:16 ||
> 
> 11.6x k-means++, 1.8x k-means
> 
> 3k clusters:
> 
> a)
> |initialize kmeans++ centers: 1% ( 30/3000) [ ] eta 58:54:10 ||
> killed job before kmeans++ finished, re-run with |uniform| initialization:
> |kmeans iterations: 0% ( 2/1000) [ ] eta 11114:37:13 ||
> 
> b)
> |initialize kmeans++ centers: 1% ( 30/3000) [ ] eta 4:57:33 ||
> |kmeans iterations: 0% ( 2/1000) [ ] eta 6082:55:04 ||
> 
> 11.9x k-means++, 1.8x k-means
> 
> 4k clusters:
> 
> a)
> |initialize kmeans++ centers: 1% ( 40/4000) [ ] eta 72:14:05 -|
> killed job before kmeans++ finished, re-run with |uniform| initialization:
> |kmeans iterations: 0% ( 2/1000) [ ] eta 15112:29:23 ||
> 
> b)
> |initialize kmeans++ centers: 1% ( 40/4000) [ ] eta 6:55:40 -|
> |kmeans iterations: 0% ( 2/1000) [ ] eta 8842:17:33 ||
> 
> 10.4x k-means++, 1.71x k-means
> 
> 5k clusters:
> 
> a)
> |initialize kmeans++ centers: 1% ( 50/5000) [ ] eta 96:04:59 ||
> killed job before kmeans++ finished, re-run with |uniform| initialization:
> |kmeans iterations: 0% ( 2/1000) [ ] eta 19245:24:34 ||
> 
> b)
> |initialize kmeans++ centers: 1% ( 50/5000) [ ] eta 8:25:50 ||
> Converged after 2 iterations, no ETA recorded in log.
> 
> 11.4x k-means++, unknown k-means
> 
> So this has made k-means++ reasonably fast now, but the speedup of the 
> k-means itself is much lower than expected no? Again, this is 16 threads 
> - how much speedup did you expect?

Since the cluster method only parallelizes the calculation of the 
metric, the speed-up has to be lower to the much more complex kmeans++ 
method. However I think there is potential for improving this further.

**Comment by rafwiewiora** [comment]
>this should not happen, because pybind11 is a build time dependency,
which should be installed automatically upon building extension. How did
you install the development version?

Was surprised too - installed by `python setup.py install` from the repo.

>Thanks for the results, which commit id did you test?
The fixed version is 888a81c and from
the stacktrace of the matplotlib error, I see that you've tested an
outdated version (sorry). The older version also contained a bug in the
synchronization of the kmeans iteration method.

Yep yep - I started these on Friday (https://github.com/markovmodel/PyEMMA/pull/1142/commits/e6a74ec6b6330484bfff09c0b6d79bbff06994ac). I got the https://github.com/markovmodel/PyEMMA/commit/888a81c3e6fefd7b697c589eedcca36f30980b40 running now - will report results asap.

**Comment by rafwiewiora** [comment]
Results from https://github.com/markovmodel/PyEMMA/commit/888a81c3e6fefd7b697c589eedcca36f30980b40:

1k clusters:
`initialize kmeans++ centers:   1% (  10/1000) [                    ] eta 13:24 |`
`kmeans iterations:   0% (   2/1000) [                          ] eta 295:53:43 |`

76.7x k-means++, 12.7x k-means

2k clusters:
`initialize kmeans++ centers:   1% (  20/2000) [                    ] eta 20:57 -`
`kmeans iterations:   0% (   2/1000) [                          ] eta 598:27:16 |`

101.7x k-means++, 12.4x k-means

3k clusters:
`initialize kmeans++ centers:   1% (  30/3000) [                  ] eta 1:26:46 |`
`kmeans iterations:   0% (   2/1000) [                          ] eta 939:59:01 |`

41x k-means++, 11.8x k-means

4k clusters:
`initialize kmeans++ centers:  10% ( 400/4000) [#                 ] eta 1:37:36 -`
k-means hasn't started yet

44.7x k-means++, unknown k-means

5k clusters:
`initialize kmeans++ centers:   1% (  50/5000) [                  ] eta 3:27:16 |`
k-means hasn't started yet

27.8x k-means++, unknown k-means

Nice!!!

**Comment by marscher** [comment]
Thanks for benchmarking this! Really appreciated. The results look
promising.

@clonker:
I still don't understand why the loop invariant in kmeans++
(centers_counter == k) does not hold for the TestPipeline.test_chunksize
test, which runs Minibatch Kmeans.
